FROM node:6

LABEL maintainer="gkolve@gmail.com" \
      description="Honey data API v2 for Droplist" \

ARG NODE_ENV
ENV NODE_ENV "$NODE_ENV"

RUN npm install --quiet

WORKDIR /opt/app
COPY package*.json ./
COPY index.js ./
COPY src ./src/

EXPOSE 8080

ENTRYPOINT ["npm"]